name: update-version

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # Midnight - every night

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Update GITHUB_CLI_VERSION

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}

      - name: Get latest gh version
        run: |
          gh_version="$(curl --silent "https://api.github.com/repos/cli/cli/releases/latest" | grep -Po '"tag_name": "(v)?\K.*?(?=")')"
          echo "gh_version=${gh_version}" >> $GITHUB_ENV

      - name: Update GITHUB_CLI_VERSION
        run: |
          echo "${{ env.gh_version }}" | grep -Eq "^[0-9]+\.[0-9]+\.[0-9]+$"
          find . -name Dockerfile -print0 | xargs -0 sed -i -E "s/^(ENV GITHUB_CLI_VERSION\s*).*$/\1${{ env.gh_version }}/g"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        id: "commit"
        with:
          commit_message: "Update GITHUB_CLI_VERSION to ${{ env.gh_version }}"
          commit_user_name: actions-user
          commit_user_email: actions@github.com
          commit_author: Bot <actions@github.com>

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: steps.commit.outputs.changes_detected == 'true'
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          file: ./debian/Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.gh_version }}
            ghcr.io/${{ github.repository }}:latest
